entities:
  fuzzer_1:
    args:
    - config.yaml
    binary_path: ./build/proxy/proxy_fuzzer
    exec_with: ''
    fuzzed: true
    ip: 192.168.1.40
    port: 5050
    role: fuzzer
    connections:
    - src_ip: 192.168.1.10
      src_port: 5000
      port_src_proxy: 51379
      dst_ip: 192.168.1.11
      dst_port: 5001
      port_dst_proxy: 20953
    - src_ip: 192.168.1.10
      src_port: 5000
      port_src_proxy: 57257
      dst_ip: 192.168.1.12
      dst_port: 5000
      port_dst_proxy: 47742
  udp_entity1:
    args:
    - 192.168.1.10:5000
    - 192.168.1.11:5001
    - 192.168.1.12:5000
    binary_path: ./tests/udp_infinite_loop/main.py
    destinations:
    - ip: 192.168.1.11
      port: 5001
    - ip: 192.168.1.12
      port: 5000
    exec_with: python3
    fuzzed: true
    ip: 192.168.1.10
    port: 5000
    protocol: udp
    role: hybrid
  udp_entity2:
    args:
    - 192.168.1.11:5001
    - 192.168.1.10:5000
    binary_path: ./tests/udp_infinite_loop/main.py
    destinations:
    - ip: 192.168.1.10
      port: 5000
    exec_with: python3
    fuzzed: true
    ip: 192.168.1.11
    port: 5001
    protocol: udp
    role: hybrid
  udp_entity3:
    args:
    - 192.168.1.12:5000
    - 192.168.1.10:5000
    binary_path: ./tests/udp_infinite_loop/main.py
    destinations:
    - ip: 192.168.1.10
      port: 5000
    exec_with: python3
    fuzzed: true
    ip: 192.168.1.12
    port: 5000
    protocol: udp
    role: hybrid
general:
  log_dir: logs/
  log_level: INFO
network:
  docker_network_name: mitm_net
  gateway: 192.168.1.1
  subnet: 192.168.1.0/24
