general:
  log_level: "INFO"                      
  log_dir: logs/                         

network:
  docker_network_name: mitm_net         
  subnet: 192.168.1.0/24                
  gateway: 192.168.1.1                  

entities:
  udp_entity1:
    role: hybrid                        
    protocol: udp
    ip: 192.168.1.10                    
    port: 5000                          
    fuzzed: true                       
    exec_with: python3                  
    binary_path: ./tests/udp_infinite_loop/main.py 
    args: [192.168.1.10:5000, 192.168.1.11:5001]                            
    destinations:                       
      - ip: 192.168.1.11
        port: 5001

  udp_entity2:
    role: hybrid
    protocol: udp
    ip: 192.168.1.11
    port: 5001
    fuzzed: true
    exec_with: python3
    binary_path: ./tests/udp_infinite_loop/main.py 
    args: [192.168.1.11:5001, 192.168.1.10:5000]
    destinations:
      - ip: 192.168.1.10
        port: 5000

  fuzzer_1:
    role: fuzzer
    ip: 192.168.1.40
    port: 5050
    fuzzed: true
    exec_with: ""                      
    binary_path: ./bin/fuzzer_1
    args: [config.yaml]
