general:
  log_level: INFO
  log_dir: logs/
network:
  docker_network_name: mitm_net
  subnet: 192.168.1.0/24
  gateway: 192.168.1.1
entities:
  tcp_client:
    role: client
    protocol: tcp
    ip: 192.168.1.20
    port: -1
    fuzzed: true
    binary_path: tests/TCP-Infinite-Loop/client.py
    args: []
    exec_with: python3
    connect_to:
      ip: 192.168.1.10
      port: 12345
  tcp_server:
    role: server
    protocol: tcp
    ip: 192.168.1.10
    port: 12345
    fuzzed: true
    binary_path: tests/TCP-Infinite-Loop/server.py
    exec_with: python3
    args: []
  fuzzer_1:
    role: fuzzer
    ip: 192.168.1.40
    port: 5050
    fuzzed: true
    exec_with: ''
    binary_path: ./build/proxy/proxy_fuzzer
    args:
    - config.yaml
    connections: []
    tcp_redirections:
    - server_ip: 192.168.1.10
      server_port: 12345
      proxy_port: 22571
