FROM python:3.9-slim

# Instalare pachete esențiale pentru TPROXY, debugging și YAML
RUN apt-get update && \
    apt-get install -y \
        libyaml-cpp0.7 \
        iptables \
        iproute2 \
        iputils-ping \
        net-tools \
        procps \
        tcpdump \
        curl \
        vim \
        less \
        gdb \
        nano && \
    apt-get clean

WORKDIR /app

COPY . /app

# <ENTRYPOINT>

# <EXEC_COMMAND>
