FROM python:3.9-slim

# Custom pre-requities
RUN apt-get update && apt-get install -y libyaml-cpp0.7


# Set working directory
WORKDIR /app

# Copy entire project into the container
COPY . /app

# Run entrypoint script (generates iptables rules then execs CMD)
# <ENTRYPOINT>

# Default command to launch the application
# <EXEC_COMMAND>
