FROM python:3.9-slim

# Instalare pachete esențiale pentru TPROXY, debugging și YAML
RUN apt-get update && \
    apt-get install -y \
        libyaml-cpp0.7 \
        iptables \
        iproute2 \
        iputils-ping \
        net-tools \
        procps \
        tcpdump \
        curl \
        vim \
        less \
        nano && \
    apt-get clean

# Setare director de lucru
WORKDIR /app

# Copiere cod sursă
COPY . /app

# Scriptul de entrypoint (va genera regulile iptables & tproxy)
# <ENTRYPOINT>

# Comanda implicită (va fi suprascrisă din commander.py)
# <EXEC_COMMAND>
