FROM python:3.9-slim

# Custom pre-requities
RUN apt-get update && apt-get install -y libyaml-cpp0.7


# Set working directory
WORKDIR /app

# Copy entire project into the container
COPY . /app

# Run entrypoint script (generates iptables rules then execs CMD)
COPY docker/entrypoint_fuzzer_1.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# Default command to launch the application
CMD ["tail", "-f", "/dev/null"]
