general:
  log_level: "INFO"                      
  log_dir: logs/                         

network:
  docker_network_name: mitm_net         
  subnet: 192.168.1.0/24                
  gateway: 192.168.1.1                  

entities:
  udp_entity1:
    role: hybrid                        
    protocol: udp
    ip: 192.168.1.10                    
    port: 9999                          
    fuzzed: true                       
    exec_with: python3                  
    binary_path: ./tests/UDP_Dificulty_1/test_echo/server.py
    args: []                          
    destinations:                       
      - ip: 192.168.1.20
        port: -1
      - ip: 192.168.1.30
        port: -1

  udp_entity2:
    role: hybrid                        
    protocol: udp
    ip: 192.168.1.20                    
    port: -1                          
    fuzzed: true                       
    exec_with: python3                  
    binary_path: ./tests/UDP_Dificulty_1/test_echo/client.py
    args: []                          
    destinations:                       
      - ip: 192.168.1.10
        port: 9999

  udp_entity3:
    role: hybrid                        
    protocol: udp
    ip: 192.168.1.30                    
    port: -1                          
    fuzzed: true                       
    exec_with: python3                  
    binary_path: ./tests/UDP_Dificulty_1/test_echo/client.py
    args: []                          
    destinations:                       
      - ip: 192.168.1.10
        port: 9999

  fuzzer_1:
    role: fuzzer
    ip: 192.168.1.40
    port: 5050
    fuzzed: true
    exec_with: ""                      
    binary_path: ./build/proxy/proxy_fuzzer
    args: [config.yaml]
