general:
  log_level: INFO
  log_dir: logs/
network:
  docker_network_name: mitm_net
  subnet: 192.168.1.0/24
  gateway: 192.168.1.1
entities:
  udp_primary:
    role: receiver
    protocol: udp
    ip: 192.168.1.11
    port: 5000
    fuzzed: true
    exec_with: ''
    binary_path: ./build/tests/vuln-udp-dynamic-port-entity/server_primary
    args: []
    destinations:
    - ip: 192.168.1.10
      port: -1
    - ip: 192.168.1.12
      port: -1
  udp_client:
    role: sender
    protocol: udp
    ip: 192.168.1.10
    port: -1
    fuzzed: true
    exec_with: ''
    binary_path: ./build/tests/vuln-udp-dynamic-port-entity/client_dynamic
    args:
    - 192.168.1.11
    destinations:
    - ip: 192.168.1.11
      port: 5000
  udp_client2:
    role: sender
    protocol: udp
    ip: 192.168.1.12
    port: -1
    fuzzed: true
    exec_with: ''
    binary_path: ./build/tests/vuln-udp-dynamic-port-entity/client_dynamic
    args:
    - 192.168.1.11
    destinations:
    - ip: 192.168.1.11
      port: 5000
  fuzzer_1:
    role: fuzzer
    ip: 192.168.1.40
    port: 5050
    fuzzed: true
    exec_with: ''
    binary_path: ./build/proxy/proxy_fuzzer
    args:
    - config.yaml

