general:
  log_level: INFO
  log_dir: logs/
network:
  docker_network_name: mitm_net
  subnet: 192.168.1.0/24
  gateway: 192.168.1.1
entities:
  udp_server:
    role: receiver
    protocol: udp
    ip: 192.168.1.10
    port: 9999
    fuzzed: true
    exec_with: ''
    binary_path: ./build/tests/vuln-udp-stack-overflow/server-stack-overflow
    args: []
    destinations:
    - ip: 192.168.1.10
      port: -1
  udp_client:
    role: sender
    protocol: udp
    ip: 192.168.1.20
    port: -1
    fuzzed: true
    exec_with: ''
    binary_path: ./build/tests/vuln-udp-stack-overflow/client-stack-overflow
    args:
    - 192.168.1.11
    - 9999
    destinations:
    - ip: 192.168.1.10
      port: 9999
  fuzzer_1:
    role: fuzzer
    ip: 192.168.1.40
    port: 5050
    fuzzed: true
    exec_with: ''
    binary_path: ./build/proxy/proxy_fuzzer
    args:
    - config.yaml

