general:
  log_level: INFO
  log_dir: logs/
network:
  docker_network_name: mitm_net
  subnet: 192.168.1.0/24
  gateway: 192.168.1.1
entities:
  tcp_client:
    role: client                    
    protocol: tcp
    ip: 192.168.1.10                             
    port: -1                           
    fuzzed: true                        
    binary_path:                    
    args: []                        
    exec_with: python3
    connect_to:                     
      ip: 192.168.1.20                        
      port: 9000                        

  tcp_server:
    role: server                    
    protocol: tcp
    ip: 192.168.1.20                            
    port: 9000                          
    fuzzed: true                      
    binary_path:                    
    exec_with:
    args: []   
                         
  fuzzer_1:
    role: fuzzer
    ip: 192.168.1.40
    port: 5050
    fuzzed: true
    exec_with: ''
    binary_path: ./build/proxy/proxy_fuzzer
    args:
    - config.yaml
    connections:
    - entityA_ip: 192.168.1.11
      entityA_port: 5000
      entityA_proxy_port_recv: 35117
      entityA_proxy_port_send: 21355
      entityB_ip: 192.168.1.10
      entityB_port: -1
      entityB_proxy_port_recv: 35222
      entityB_proxy_port_send: 53025


